[package]
name = "nannou-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
rand = "0.8.5"
nannou_audio = "0.18.0"
ringbuf = "0.2.2"
pitch-detection = "0.3.0"
