[package]
name = "nannou-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
nannou_audio = "0.18.0"
rand = "0.8.5"
audrey = { version = "0.3.0", features = ["wav"] }
